### ISSUE TITLE
activeIndex问题

### ISSUE THREAD

**Issue by nevergoneok** [jzoom/flutter_swiper#2]
如果在任意一个tab跳转到新的页面，当finish新的页面后，activeIndex变为0

**Comment by jzoom** [comment]
推荐这么做，使用一个变量保存一下当前的activeIndex,然后将这个变量赋值给Swiper的index，并在onIndexChanged这个回调函数中同步这个变量的值,activeIndex就变成“受控”的了。
![image](https://user-images.githubusercontent.com/6038236/41631886-ba76b1fa-7469-11e8-85ea-b55552a22e5b.png)

**Comment by trungwebsite** [comment]
It seems idex: _activeIndex you mention above only work with default layout. Tinder, Stack,.. doesn't work. Is it a bug. Please help. Thanks a lot.
